steps:
  # Step to build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloud-k8s-429121/container1', '.']

  # Step to push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloud-k8s-429121/container1']

  # Step to get cluster credentials using gcloud
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['container', 'clusters', 'get-credentials', 'assignment-cluster', '--zone', 'us-central1-a', '--project', 'cloud-k8s-429121']

  # Step to apply PV and PVC manifest
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/pv-pvc.yaml']

  # Step to apply Kubernetes deployment and service manifests
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/deployment-service.yaml']

images:
  - 'gcr.io/cloud-k8s-429121/container1'
options:
  logging: CLOUD_LOGGING_ONLY
